# .eslintrc.yml

env:
  es2021: true
  browser: true
  node: true  # Add this line to specify Node.js environment

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: 2021
  sourceType: module
